# cctv_sim/scripts/sim/config.py

FPS = 30.0

WALK_START_FRAME = 0.0
WALK_END_FRAME = 28.0

YELL_START_FRAME = 0.0
YELL_END_FRAME = 234.0

WALK_ROOT_PATH = "/World/Characters/walking_man1"
YELL_SOURCE_ROOT_PATH = "/World/Sources/yelling_man1"
GUN_SOURCE_ROOT_PATH = "/World/Sources/shooting_man1"
GUN_REPEAT_COUNT = 5
GUNSHOT_FIRE_FRAME = 5.0
GUNSHOT_FRAME_INTERVAL = 36.0

WALK_SKEL_ROOT_PATH = "/World/Characters/walking_man1/mixamorig12_Hips"
WALK_SKELETON_PATH = "/World/Characters/walking_man1/mixamorig12_Hips/Skeleton"

WALK_SOURCE_ANIM_PATH = "/World/Characters/walking_man1/mixamorig12_Hips/mixamo_com"
YELL_SOURCE_ANIM_PATH = "/World/Sources/yelling_man1/mixamorig12_Hips/mixamo_com"

WALK_LIVE_ANIM_PATH = "/World/Characters/walking_man1/mixamorig12_Hips/__LiveAnim"

WAYPOINTS = [
    (0.0,   0.0,   0.0),
    (300.0, 0.0,   0.0),
    (300.0, 0.0, 300.0),
    (0.0,   0.0, 300.0),
]

ROUTES_ROOT_PATH = "/World/Routes"
ROUTE_ROOT_PATH = "/World/Routes/MainRoute"
ROUTE_WAYPOINT_PREFIX = "wp_"
ROUTE_RECT_WALK_ENABLED = True

WALK_SPEED = 220.0
ARRIVE_DIST = 80.0
YAW_OFFSET_DEG = 90.0
KEEP_CURRENT_CHARACTER_Z = True
STREET_WALK_ENABLED = True
STREET_WALK_ROOT_PATH = "/World/assembly_City/ce_Context_City_Streets"
STREET_WALK_MIN_RECT_SIZE_M = 12.0
STREET_WALK_MARGIN_M = 20.0
STREET_WALK_TARGET_MIN_DISTANCE_M = 360.0
STREET_WALK_TARGET_MAX_DISTANCE_M = 1600.0
STREET_WALK_TARGET_ATTEMPTS = 96
STREET_WALK_SEGMENT_SAMPLE_STEP_M = 35.0
STREET_WALK_CCTV_RADIUS_M = 1600.0
STREET_WALK_ESCAPE_TARGET_ATTEMPTS = 8
GUN_ESCAPE_SPEED_MULTIPLIER = 2.0
GUN_ESCAPE_REMOVE_SEC = 10.0

EVENT_ROOT_PATH = "/World/Events"
MINIMAP_EVENT_ROOT_PATH = EVENT_ROOT_PATH
CAR_CRASH_POINTS_ROOT_PATH = "/World/Events/CarCrash"
CAR_CRASH_ASSET_PREFIX = "crash_"
CAR_CRASH_VISIBLE_SEC = 5.0
EXPLOSION_POINTS_ROOT_PATH = "/World/Events/Explosion"
EXPLOSION_SOURCE_ROOT_PATHS = ("/World/Explosion", EXPLOSION_POINTS_ROOT_PATH)
EXPLOSION_LIVE_ROOT_PATH = "/World/Events/ExplosionUSD"
EXPLOSION_USD_FPS = 30.0
EXPLOSION_USD_SCALE = 1.0
EXPLOSION_USD_ROTATE_XYZ = (90.0, 0.0, 0.0)
EXPLOSION_POSITION_OFFSET = (0.0, 0.0, -50.0)
CCTV_ROOT_PATH = "/World/CCTV"
CHARACTER_ROOT_PATH = "/World/Characters"
SOURCE_ROOT_PATH = "/World/Sources"
SOUND_SOURCE_MARKER_ROOT_PATH = "/World/SoundSources"
MICROPHONE_ROOT_PATH = "/World/Microphones"
VEHICLE_ROOT_PATH = "/World/Vehicles"
PEDESTRIAN_ROOT_PATH = "/World/Pedestrians"
EGO_VEHICLE_PATHS = (
    "/World/EgoVehicle",
    "/World/Vehicles/EgoVehicle",
    "/World/Vehicles/ego_vehicle",
)

CCTV_SCALE = 1.0
SOUND_DETECTION_RADIUS_M = 5000.0
CCTV_CAMERA_FORWARD_YAW_DEG = 150.0
CCTV_AIM_DURATION_SEC = 1.0
CCTV_EVENT_HOLD_SEC = 5.0
CCTV_RETURN_DURATION_SEC = 1.0
CCTV_HOME_REFERENCE_PRIM_SUFFIX = "Rig/Geom/Pole/Luminaire_Head"
CCTV_HOME_REFERENCE_FORWARD_AXIS = (0.0, 1.0, 0.0)
CCTV_APPLY_HOME_ON_SETUP = True
CCTV_ZOOM_NEAR_DISTANCE_M = 500.0
CCTV_ZOOM_FAR_DISTANCE_M = SOUND_DETECTION_RADIUS_M
CCTV_WIDE_FOCAL_LENGTH = 8.0
CCTV_TELE_FOCAL_LENGTH = 28.0
CCTV_VIEW_CAMERA_TRANSLATE = (0.0, 34.0, 0.0)
CCTV_VIEW_CAMERA_ROTATE_XYZ = (90.0, 0.0, 0.0)
CCTV_VIEW_CAMERA_FOCAL_LENGTH = 8.0
CCTV_VIEW_CAMERA_HORIZONTAL_APERTURE = 20.955
CCTV_VIEW_CAMERA_CLIPPING_RANGE = (1.0, 100000.0)
CCTV_MONITOR_LIVE_ON_START = False
CCTV_MONITOR_MAX_FPS = 30
SOUND_SOURCE_VISIBLE_SEC = 5.0

MINIMAP_WINDOW_TITLE = "Stage Minimap"
MINIMAP_WINDOW_WIDTH = 360
MINIMAP_WINDOW_HEIGHT = 420
MINIMAP_MAP_WIDTH = 300
MINIMAP_MAP_HEIGHT = 300
MINIMAP_LIVE_ON_START = True
MINIMAP_MAX_FPS = 10
MINIMAP_UPDATE_INTERVAL_SEC = 0.1
MINIMAP_SCAN_INTERVAL_SEC = 1.0
MINIMAP_EXTENT_PADDING = 60.0
MINIMAP_CCTV_EXTENT_MARGIN = 120.0
MINIMAP_CCTV_MIN_SPAN = 720.0
MINIMAP_MAX_MARKERS_PER_TYPE = 48
MINIMAP_BACKGROUND_FEATURE_LIMIT = 96
MINIMAP_BACKGROUND_MIN_PIXEL_SIZE = 2.0
MINIMAP_BACKGROUND_MAX_AREA_RATIO = 0.92
MINIMAP_FALLBACK_EXTENT = {
    "min_x": -650.0,
    "max_x": 650.0,
    "min_y": -650.0,
    "max_y": 650.0,
}
MINIMAP_CAMERA_PATH = "/World/Minimap/MinimapTopCamera"
MINIMAP_CAMERA_FOCAL_LENGTH = 24.0
MINIMAP_CAMERA_HORIZONTAL_APERTURE = 20.955
MINIMAP_CAMERA_CLIPPING_RANGE = (1.0, 200000.0)
MINIMAP_CAMERA_FRAME_MARGIN = 3.45
MINIMAP_CAMERA_MIN_HEIGHT = 600.0
MINIMAP_CAPTURE_FILENAME = "stage_minimap_static.png"

FOLLOW_TOP_CAMERA_RIG_NAME = "CCTV_FollowTopCamRig"
FOLLOW_TOP_CAMERA_NAME = "TopCamera"
FOLLOW_TOP_CAMERA_VISUAL_NAME = "CrazyflieVisual"
FOLLOW_TOP_CAMERA_FIXED_HEIGHT = 20.0
FOLLOW_TOP_CAMERA_FOCAL_LENGTH = 2.0
FOLLOW_TOP_CAMERA_HORIZONTAL_APERTURE = 20.955
FOLLOW_TOP_CAMERA_FRAME_MARGIN = 1.1
FOLLOW_TOP_CAMERA_VIEWPORT_ASPECT = (16.0, 9.0)
FOLLOW_TOP_CAMERA_CLIPPING_RANGE = (0.1, 100000.0)
FOLLOW_TOP_CAMERA_AUTO_BIND_ON_START = False
FOLLOW_TOP_CAMERA_AUTO_TRACK_EVENTS = True
FOLLOW_TOP_CAMERA_MOVE_DURATION_SEC = 1.5
FOLLOW_TOP_CAMERA_MOVE_SPEED = 900.0
FOLLOW_TOP_CAMERA_CHASE_SPEED = 1400.0
FOLLOW_TOP_CAMERA_MOVE_MAX_TRAVEL_SEC = 2.0
FOLLOW_TOP_CAMERA_CHASE_MAX_TRAVEL_SEC = 0.75
FOLLOW_TOP_CAMERA_VISUAL_SCALE = 75.0
FOLLOW_TOP_CAMERA_CAMERA_LOCAL_OFFSET = (0.0, 0.0, -0.2)
FOLLOW_TOP_CAMERA_CAMERA_ROTATE_XYZ_Z_UP = (0.0, 0.0, 0.0)
FOLLOW_TOP_CAMERA_CAMERA_ROTATE_XYZ_Y_UP = (-90.0, 0.0, 0.0)
CRAZYFLIE_ASSET_CANDIDATES = (
    "https://omniverse-content-production.s3.us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Robots/Bitcraze/Crazyflie/cf2x.usd",
    "omniverse://localhost/NVIDIA/Assets/Isaac/5.0/Isaac/Robots/Bitcraze/Crazyflie/cf2x.usd",
    "omniverse://localhost/NVIDIA/Assets/Isaac/4.5/Isaac/Robots/Bitcraze/Crazyflie/cf2x.usd",
    "omniverse://localhost/NVIDIA/Assets/Isaac/Robots/Bitcraze/Crazyflie/cf2x.usd",
    "omniverse://localhost/NVIDIA/Assets/Isaac/Robots/Bitcraze/Crazyflie/cf2x/cf2x.usda",
    "omniverse://localhost/NVIDIA/Assets/Isaac/Robots/Crazyflie/cf2x.usd",
)
USER_DEFINED_CRAZYFLIE_PATH = "https://omniverse-content-production.s3.us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Robots/Bitcraze/Crazyflie/cf2x.usd"

AWARENESS_ROOT_PATH = "/World/SituationAwareness"
AWARENESS_EVENT_VISIBLE_SEC = 8.0
AWARENESS_EVENT_HISTORY_LIMIT = 8
AWARENESS_MAP_WIDTH = 400
AWARENESS_MAP_HEIGHT = 240
AWARENESS_MAP_CAMERA_PATH = "/World/SituationAwareness/MinimapCamera"
AWARENESS_MAP_CAMERA_HEIGHT_M = 8000.0
AWARENESS_MAP_CAMERA_CLIPPING_RANGE = (1.0, 20000.0)
AWARENESS_MAP_CAMERA_APERTURE_SCALE = 10.0
AWARENESS_MAP_VIEWPORT_FPS = 0
AWARENESS_MARKER_RADIUS_M = 18.0
AWARENESS_EVENT_MARKER_OPACITY = 0.08
AWARENESS_EVENT_UI_OPACITY = 0x18
AWARENESS_PULSE_MIN_RADIUS_M = 28.0
AWARENESS_PULSE_MAX_RADIUS_M = 110.0
AWARENESS_PULSE_PERIOD_SEC = 1.6
AWARENESS_PULSE_FILL_HEIGHT_M = 1.0
AWARENESS_PULSE_FILL_OPACITY = 0.05
AWARENESS_LINK_HEIGHT_M = 18.0
AWARENESS_CCTV_LINK_WIDTH_M = 12.0
AWARENESS_CCTV_LINK_OPACITY = 0.03
AWARENESS_PANEL_REFRESH_SEC = 0.15

CCTV_PLACEMENTS = [
    {"name": "cctv_01", "position": (-120.0, -120.0, 0.0), "yaw": 45.0, "pitch": 12.0, "scale": CCTV_SCALE},
    {"name": "cctv_02", "position": (420.0, -120.0, 0.0), "yaw": 135.0, "pitch": 12.0, "scale": CCTV_SCALE},
    {"name": "cctv_03", "position": (420.0, 420.0, 0.0), "yaw": -135.0, "pitch": 12.0, "scale": CCTV_SCALE},
    {"name": "cctv_04", "position": (-120.0, 420.0, 0.0), "yaw": -45.0, "pitch": 12.0, "scale": CCTV_SCALE},
]

# City Demo Asset: Z-up
UP_AXIS = "Z"

# Character axis correction
CHAR_BASE_ROT_X = 90.0
CHAR_BASE_ROT_Y = 0.0
CHAR_BASE_ROT_Z = 0.0

# 필요하면 나중에 조정
CHAR_SCALE = 1.0
CHAR_GROUND_CLEARANCE = 2.0
GROUND_Z = 0.0
